// JSOW v9 - Quizzes
const Q=[
{ci:2,q:"Which is an example of a full-bodied red wine?",o:["Pinot Grigio","Cabernet Sauvignon","Beaujolais","Vinho Verde"],a:1,e:"Cabernet Sauvignon is deeply coloured, high in tannin, and full-bodied."},
{ci:2,q:"Which is true of Port?",o:["Always sweet and high in alcohol","Always dry and high in alcohol","Can be dry, medium, or sweet","Same as Sherry"],a:0,e:"Spirit is added during fermentation, leaving residual sugar. Port is always sweet."},
{ci:2,q:"Which grape part provides red wine with its colour?",o:["Seeds","Pulp","Skins","Stems"],a:2,e:"Skins contain anthocyanin pigments, extracted during maceration."},
{ci:2,q:"What converts grape juice into wine?",o:["Distillation","Alcoholic fermentation","Pasteurisation","Carbonation"],a:1,e:"Yeast converts sugars into alcohol and CO₂ during fermentation."},
{ci:2,q:"Chilli heat in food makes wine seem...",o:["Drier and fuller","More fruity and sweeter","Less bitter","More drying, more bitter, hotter"],a:3,e:"Chilli heat amplifies the perception of alcohol's burning sensation."},
{ci:2,q:"Light-bodied red wine should be served at approximately...",o:["6–8°C","7–10°C","13°C","18°C"],a:2,e:"Light reds are best slightly chilled at around 13°C."},
{ci:2,q:"Why is acidity important in wine?",o:["It is sour and should be avoided","It creates alcohol","It gives wine a refreshing characteristic","It adds sweetness"],a:2,e:"Acidity provides freshness and balance, making wine food-friendly."},
{ci:2,q:"Which of these is a black (red) grape?",o:["Riesling","Syrah","Chardonnay","Pinot Grigio"],a:1,e:"Syrah/Shiraz is a black grape producing deeply coloured red wines."},
{ci:2,q:"What is the ideal storage temperature for wine?",o:["0–5°C","10–15°C","18–22°C","25–30°C"],a:1,e:"10–15°C with consistent temperature is ideal for wine storage."},
{ci:2,q:"Sparkling wines get their bubbles from...",o:["Adding carbonated water","A secondary fermentation","Boiling the wine","Adding citric acid"],a:1,e:"A second fermentation produces CO₂ that dissolves in the wine."},
{ci:2,q:"Which tasting note best describes Pinot Noir?",o:["High acid, low tannin, blackcurrant, pepper","Low acid, high tannin, red fruits","High acid, high tannin, red fruit","High acid, low tannin, red cherry and strawberry"],a:3,e:"Pinot Noir has high acidity, low-medium tannin, with delicate red cherry and strawberry."},
{ci:2,q:"Rosé wine gets its pink colour from...",o:["Mixing red and white wine","Adding food colouring","Brief skin contact with red grapes","Using pink grapes"],a:2,e:"Red grape skins are left in contact with juice briefly, then pressed off."},
{ci:2,q:"Which wine style uses the Traditional Method?",o:["Prosecco","Port","Champagne","Sherry"],a:2,e:"Champagne undergoes secondary fermentation in bottle (Traditional Method)."},
{ci:2,q:"Cork taint (TCA) makes wine smell like...",o:["Vinegar","Rotten eggs","Wet cardboard / musty basement","Burnt rubber"],a:2,e:"TCA produces a musty, damp cardboard aroma, stripping fruit character."},
{ci:2,q:"The WSET SAT assesses wine in which order?",o:["Nose, Palate, Appearance","Palate, Appearance, Nose","Appearance, Nose, Palate","Appearance, Palate, Nose"],a:2,e:"SAT follows: Appearance → Nose → Palate → Conclusion."},
{ci:3,q:"Marlborough, New Zealand is most famous for which grape?",o:["Chardonnay","Pinot Noir","Sauvignon Blanc","Riesling"],a:2,e:"Marlborough produces ~85% of NZ wine, dominated by pungent Sauvignon Blanc."},
{ci:3,q:"Barolo is made from which grape variety?",o:["Sangiovese","Nebbiolo","Barbera","Corvina"],a:1,e:"Barolo DOCG requires 100% Nebbiolo, grown in Piedmont, Italy."},
{ci:3,q:"What gives Champagne its bubbles?",o:["Added CO₂","Primary fermentation","Secondary fermentation in bottle","Carbonated water"],a:2,e:"The Traditional Method: secondary fermentation occurs inside the sealed bottle."},
{ci:3,q:"Which German Prädikat level indicates noble rot?",o:["Kabinett","Spätlese","Auslese","Beerenauslese and TBA"],a:3,e:"BA and TBA are made from individually selected botrytis-affected berries."},
{ci:3,q:"Châteauneuf-du-Pape is known for which grape?",o:["Syrah","Cabernet Sauvignon","Grenache","Merlot"],a:2,e:"Grenache is the dominant variety in CdP, with up to 13 varieties permitted."},
{ci:3,q:"Riesling is most associated with which country?",o:["France","Italy","Germany","Spain"],a:2,e:"Germany is Riesling's homeland — Mosel, Rheingau, Pfalz, and Nahe."},
{ci:3,q:"What does malolactic conversion do?",o:["Increases acidity","Converts malic acid to softer lactic acid","Adds sweetness","Removes tannin"],a:1,e:"MLF converts sharp malic acid to softer lactic acid, adding creaminess."},
{ci:3,q:"Chianti Classico DOCG is made primarily from...",o:["Nebbiolo","Tempranillo","Sangiovese","Corvina"],a:2,e:"Chianti Classico requires a minimum of 80% Sangiovese."},
{ci:3,q:"Which white grape is most planted in South Africa?",o:["Sauvignon Blanc","Chardonnay","Chenin Blanc","Riesling"],a:2,e:"Chenin Blanc (locally called Steen) is SA's most planted white variety."},
{ci:3,q:"How does altitude affect grape growing?",o:["Higher = warmer","Higher = cooler, preserving acidity","Higher always = sweeter grapes","No impact"],a:1,e:"Every 100m of altitude rise drops temperature by ~0.6°C, preserving acidity."},
{ci:3,q:"Prosecco is made using which method?",o:["Traditional Method","Tank/Charmat Method","Asti Method","Carbonation"],a:1,e:"Prosecco undergoes secondary fermentation in pressurised tanks (Charmat)."},
{ci:3,q:"Which Bordeaux bank is Merlot-dominant?",o:["Left Bank (Médoc)","Right Bank (Saint-Émilion, Pomerol)","Both equally","Neither"],a:1,e:"The Right Bank's clay/limestone soils favour Merlot over Cabernet."},
{ci:3,q:"Fino Sherry is aged under...",o:["Oak chips","A layer of flor yeast","Botrytis","Charcoal"],a:1,e:"Flor is a film of yeast that protects Fino from oxidation."},
{ci:3,q:"The 'heartbreak grape' refers to...",o:["Cabernet Sauvignon","Chardonnay","Pinot Noir","Merlot"],a:2,e:"Pinot Noir is thin-skinned, disease-prone, and notoriously difficult to grow."},
{ci:3,q:"Which Australian region is famous for Riesling?",o:["Barossa Valley","Clare Valley","Margaret River","Hunter Valley"],a:1,e:"Clare Valley and Eden Valley produce benchmark Australian Riesling."},
{ci:3,q:"What effect does new oak have on wine?",o:["Makes it more acidic","Adds vanilla, toast, and spice flavours","Removes tannin","Makes it lighter"],a:1,e:"New oak imparts vanilla, toast, coconut, clove, and spice."},
{ci:3,q:"Rioja Gran Reserva has the longest oak requirement?",o:["True","False","Same as Crianza","Only for whites"],a:0,e:"Gran Reserva requires minimum 2 years in oak, not released until 6th year."},
{ci:3,q:"Gewürztraminer is characterised by aromas of...",o:["Grass and gooseberry","Lychee and rose petal","Blackcurrant and cedar","Lemon and mineral"],a:1,e:"Gewürztraminer is intensely aromatic with exotic lychee, rose petal, ginger."},
{ci:3,q:"Malbec is most associated with which country?",o:["Chile","Australia","Argentina","France"],a:2,e:"Argentina's Mendoza region produces world-class Malbec at high altitude."},
{ci:3,q:"Key difference between Port and Sherry fortification?",o:["Port uses grape spirit, Sherry uses brandy","Port: spirit during fermentation; Sherry: after","Port is from Spain","No difference"],a:1,e:"Port: spirit during (sweet). Sherry: spirit after (dry base wine)."},
{ci:3,q:"Which food element makes tannic wine taste more bitter?",o:["Salt","Fat/protein","Umami","Acidity"],a:2,e:"Umami intensifies the perception of bitterness, tannin, and alcohol."},
{ci:3,q:"Coonawarra is famous for which combination?",o:["Shiraz on granite","Chardonnay on chalk","Cabernet Sauvignon on terra rossa","Riesling on slate"],a:2,e:"Coonawarra's red terra rossa soil over limestone produces distinctive Cabernet."},
{ci:3,q:"Amarone della Valpolicella is made by...",o:["Late harvest","Drying grapes before fermentation","Noble rot","Freezing grapes"],a:1,e:"Grapes are dried for months (appassimento), concentrating sugars and flavours."},
{ci:3,q:"Which Burgundy classification is the highest?",o:["Regional","Village","Premier Cru","Grand Cru"],a:3,e:"Grand Cru vineyards have their own appellation and produce Burgundy's finest wines."},
{ci:3,q:"The Solera system is used in production of...",o:["Champagne","Port","Sherry","Barolo"],a:2,e:"Solera is a fractional blending system unique to Sherry production."},
{ci:4,q:"Which yeast is most commonly used in winemaking?",o:["Brettanomyces","Saccharomyces cerevisiae","Trichloroanisole","Geotrichum"],a:1,e:"Saccharomyces cerevisiae is the primary fermentation yeast."},
{ci:4,q:"Which fault smells like nail polish remover?",o:["Cork taint","Oxidation","Hydrogen sulfide","Volatile acidity"],a:3,e:"Volatile acidity (ethyl acetate) produces nail polish remover aromas."},
{ci:4,q:"Which best describes a Tawny Port?",o:["Pale, dry, fresh almonds","Orange-brown, medium-sweet, dried fruits and toffee","Deep purple, sweet, plum","Near-black, coffee and prunes"],a:1,e:"Extended oxidative barrel ageing gives Tawny its amber colour and nutty character."},
{ci:4,q:"What is the alcohol range for medium-alcohol wine?",o:["Under 11%","11–13.9%","14–16%","Over 16%"],a:1,e:"WSET defines medium alcohol as 11–13.9% ABV."},
{ci:4,q:"Diacetyl (buttery flavour) comes from...",o:["Cool climate growing","Malolactic conversion","Brettanomyces","Primary fermentation"],a:1,e:"MLF produces diacetyl, responsible for butter and butterscotch aromas."},
{ci:4,q:"Which pair increases perception of bitterness and tannin?",o:["Acidity and salt","Bitterness and sweetness","Chilli heat and umami","Salt and sweetness"],a:2,e:"Both chilli heat and umami amplify bitterness, tannin, and alcohol perception."},
{ci:4,q:"How many buds are typically retained with cane pruning?",o:["2 to 3","4 to 7","8 to 20","Depends on vintage"],a:2,e:"Cane pruning retains 8–20 buds, common in Burgundy and Champagne."},
{ci:4,q:"A bottle-aged white wine would best show...",o:["Pale gold with leather aromas","Pale tawny with vanilla","Medium gold with honey and dried apricot","Medium gold with oystershell"],a:2,e:"Bottle-aged whites develop deeper gold colour with honey, dried fruit, toast."},
{ci:4,q:"New oak vs neutral oak — what is the difference?",o:["New oak extracts less flavour","New oak is only for whites","New oak adds vanilla, toast, spice; old oak mainly adds texture","New oak makes wine more acidic"],a:2,e:"New oak imparts strong flavours; old oak provides gentle oxidation and texture."},
{ci:4,q:"Which region is NOT popular for Pinot Noir?",o:["Burgundy","Central Otago","Stellenbosch","Tasmania"],a:2,e:"Stellenbosch is known for Cabernet and Bordeaux blends, not Pinot Noir."},
{ci:4,q:"The Asti Method involves...",o:["Secondary fermentation in bottle","Fermentation stopped in pressurised tank","Fermentation in oak","Adding grape spirit"],a:1,e:"The Asti Method captures CO₂ from a single fermentation stopped early."},
{ci:4,q:"Méthode Cap Classique is used in...",o:["Champagne","Rioja","South Africa","Burgundy"],a:2,e:"MCC is South Africa's term for Traditional Method sparkling wine."},
{ci:4,q:"Higher altitude effect on grapes?",o:["Warmer, faster ripening","Cooler, slower ripening, more UV","No significant effect","Higher humidity"],a:1,e:"Higher altitude = cooler but more intense UV, producing thick-skinned grapes."},
{ci:4,q:"Continental climates are characterised by...",o:["Consistent mild temperatures","Large temperature differences between seasons","Cool, damp conditions","Hot, humid summers"],a:1,e:"Continental climates have warm/hot summers and cold winters."},
{ci:4,q:"Which is NOT a factor in WSET quality assessment?",o:["Balance","Complexity","Price","Length of finish"],a:2,e:"WSET assesses quality by balance, intensity, complexity, and length — not price."},
{ci:4,q:"Pétrus is made from...",o:["100% Cabernet Sauvignon","100% Merlot","Pinot Noir","Nebbiolo"],a:1,e:"Château Pétrus in Pomerol is virtually 100% Merlot on clay soil."},
{ci:4,q:"Blanc de Blancs Champagne is...",o:["Made from black grapes only","Made from 100% Chardonnay","A non-vintage blend","Aged without dosage"],a:1,e:"Blanc de Blancs ('white from whites') is exclusively Chardonnay."},
{ci:4,q:"In the WSET L3 tasting exam, you must assess...",o:["One wine in 15 minutes","Two wines (white + red) in 30 minutes","Three wines in 45 minutes","Five wines in 60 minutes"],a:1,e:"Unit 2 requires blind tasting of two wines using SAT in 30 minutes."},
{ci:4,q:"Which soil type is associated with Chablis?",o:["Granite","Terra rossa","Kimmeridgian limestone and clay","Slate"],a:2,e:"Chablis' Kimmeridgian limestone gives wines their mineral character."},
{ci:4,q:"Minimum ageing requirement for Barolo DOCG?",o:["1 year","2 years","3 years (including 18 months in oak)","5 years"],a:2,e:"Barolo requires minimum 38 months ageing, of which 18 months in oak."}
];

// ── BADGES ──
